spring:
  security:
    oauth2:
      client:
        registration:
          google:
            # 깃허브, 외부사이트, AI 등 절대 외부 유출 금지
            # 환경 변수로 설정
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}