ALTER TABLE users ADD COLUMN due_soon_push_enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN chore_completed_push_enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN notice_push_enabled BOOLEAN NOT NULL DEFAULT FALSE;
