CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(20) NOT NULL,
    provider_user_id VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    password VARCHAR(255),
    nickname VARCHAR(255),
    CONSTRAINT uk_users_provider_user_id UNIQUE (provider, provider_user_id)
);

CREATE TABLE sharing_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_sharing_groups_created_by_user
        FOREIGN KEY (created_by_user_id) REFERENCES users (id)
);

CREATE TABLE group_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL,
    joined_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_group_members_group_user UNIQUE (group_id, user_id),
    CONSTRAINT fk_group_members_group
        FOREIGN KEY (group_id) REFERENCES sharing_groups (id),
    CONSTRAINT fk_group_members_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_group_members_user_id
    ON group_members (user_id);

CREATE TABLE group_invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    code_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uk_group_invitations_code_hash UNIQUE (code_hash),
    CONSTRAINT fk_group_invitations_group
        FOREIGN KEY (group_id) REFERENCES sharing_groups (id),
    CONSTRAINT fk_group_invitations_created_by_user
        FOREIGN KEY (created_by_user_id) REFERENCES users (id)
);

CREATE INDEX idx_group_invitations_group_id
    ON group_invitations (group_id);

CREATE INDEX idx_group_invitations_expires_at
    ON group_invitations (expires_at);
