ALTER TABLE sharing_groups ADD COLUMN public_id VARCHAR(36);
ALTER TABLE sharing_groups ADD COLUMN time_zone_id VARCHAR(40);
ALTER TABLE sharing_groups ADD COLUMN week_starts_on VARCHAR(10);

UPDATE sharing_groups
SET public_id = CAST(RANDOM_UUID() AS VARCHAR(36))
WHERE public_id IS NULL;

UPDATE sharing_groups
SET time_zone_id = 'Asia/Seoul'
WHERE time_zone_id IS NULL;

UPDATE sharing_groups
SET week_starts_on = 'MONDAY'
WHERE week_starts_on IS NULL;

ALTER TABLE sharing_groups ALTER COLUMN public_id SET NOT NULL;
ALTER TABLE sharing_groups ALTER COLUMN time_zone_id SET NOT NULL;
ALTER TABLE sharing_groups ALTER COLUMN week_starts_on SET NOT NULL;
ALTER TABLE sharing_groups
    ADD CONSTRAINT uk_sharing_groups_public_id UNIQUE (public_id);

ALTER TABLE group_members ADD COLUMN public_id VARCHAR(36);
ALTER TABLE group_members ADD COLUMN status VARCHAR(20);
ALTER TABLE group_members ADD COLUMN left_at TIMESTAMP(6) WITH TIME ZONE;

UPDATE group_members
SET public_id = CAST(RANDOM_UUID() AS VARCHAR(36))
WHERE public_id IS NULL;

UPDATE group_members
SET status = 'ACTIVE'
WHERE status IS NULL;

ALTER TABLE group_members ALTER COLUMN public_id SET NOT NULL;
ALTER TABLE group_members ALTER COLUMN status SET NOT NULL;
ALTER TABLE group_members
    ADD CONSTRAINT uk_group_members_public_id UNIQUE (public_id);

CREATE TABLE chores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(36) NOT NULL,
    group_id BIGINT NOT NULL,
    created_by_membership_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    frequency VARCHAR(20) NOT NULL,
    eligibility_mode VARCHAR(30) NOT NULL,
    due_time TIME(6) NOT NULL,
    weekly_due_day VARCHAR(10),
    biweekly_anchor_date DATE,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL,
    CONSTRAINT uk_chores_public_id UNIQUE (public_id),
    CONSTRAINT fk_chores_group
        FOREIGN KEY (group_id) REFERENCES sharing_groups (id),
    CONSTRAINT fk_chores_created_by_membership
        FOREIGN KEY (created_by_membership_id) REFERENCES group_members (id)
);

CREATE INDEX idx_chores_group_active
    ON chores (group_id, active);

CREATE UNIQUE INDEX idx_chores_public_id
    ON chores (public_id);

CREATE TABLE chore_eligible_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chore_id BIGINT NOT NULL,
    membership_id BIGINT NOT NULL,
    CONSTRAINT uk_chore_eligible_members_chore_member
        UNIQUE (chore_id, membership_id),
    CONSTRAINT fk_chore_eligible_members_chore
        FOREIGN KEY (chore_id) REFERENCES chores (id),
    CONSTRAINT fk_chore_eligible_members_membership
        FOREIGN KEY (membership_id) REFERENCES group_members (id)
);

CREATE INDEX idx_chore_eligible_members_member
    ON chore_eligible_members (membership_id);

CREATE TABLE chore_occurrences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(36) NOT NULL,
    chore_id BIGINT NOT NULL,
    frequency_snapshot VARCHAR(20) NOT NULL,
    time_zone_id_snapshot VARCHAR(40) NOT NULL,
    period_start DATE NOT NULL,
    period_end_exclusive DATE NOT NULL,
    due_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    eligibility_snapshot_version INTEGER NOT NULL,
    status VARCHAR(30) NOT NULL,
    attention_reason VARCHAR(60),
    attention_since TIMESTAMP(6) WITH TIME ZONE,
    last_decision_at TIMESTAMP(6) WITH TIME ZONE,
    current_assignment_id BIGINT,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    closed_at TIMESTAMP(6) WITH TIME ZONE,
    version BIGINT NOT NULL,
    CONSTRAINT uk_chore_occurrences_public_id UNIQUE (public_id),
    CONSTRAINT uk_chore_occurrences_chore_period
        UNIQUE (chore_id, period_start),
    CONSTRAINT uk_chore_occurrences_current_assignment
        UNIQUE (current_assignment_id),
    CONSTRAINT fk_chore_occurrences_chore
        FOREIGN KEY (chore_id) REFERENCES chores (id)
);

CREATE INDEX idx_chore_occurrences_status_due
    ON chore_occurrences (status, due_at);

CREATE INDEX idx_chore_occurrences_current_assignment
    ON chore_occurrences (current_assignment_id);

CREATE TABLE occurrence_eligible_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurrence_id BIGINT NOT NULL,
    snapshot_version INTEGER NOT NULL,
    membership_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_occurrence_eligible_members_snapshot_member
        UNIQUE (occurrence_id, snapshot_version, membership_id),
    CONSTRAINT fk_occurrence_eligible_members_occurrence
        FOREIGN KEY (occurrence_id) REFERENCES chore_occurrences (id),
    CONSTRAINT fk_occurrence_eligible_members_membership
        FOREIGN KEY (membership_id) REFERENCES group_members (id)
);

CREATE INDEX idx_occurrence_eligible_members_member
    ON occurrence_eligible_members (membership_id);

CREATE TABLE chore_assignment_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurrence_id BIGINT NOT NULL,
    assignee_membership_id BIGINT NOT NULL,
    sequence_number INTEGER NOT NULL,
    trigger_type VARCHAR(40) NOT NULL,
    assigned_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    ended_at TIMESTAMP(6) WITH TIME ZONE,
    end_reason VARCHAR(40),
    active_marker INTEGER,
    algorithm_version VARCHAR(30) NOT NULL,
    decision_seed BIGINT NOT NULL,
    candidate_snapshot CLOB NOT NULL,
    decision_summary VARCHAR(500) NOT NULL,
    CONSTRAINT uk_assignment_attempts_occurrence_sequence
        UNIQUE (occurrence_id, sequence_number),
    CONSTRAINT uk_assignment_attempts_one_active
        UNIQUE (occurrence_id, active_marker),
    CONSTRAINT fk_assignment_attempts_occurrence
        FOREIGN KEY (occurrence_id) REFERENCES chore_occurrences (id),
    CONSTRAINT fk_assignment_attempts_assignee
        FOREIGN KEY (assignee_membership_id) REFERENCES group_members (id)
);

CREATE INDEX idx_assignment_attempts_assignee
    ON chore_assignment_attempts (assignee_membership_id);

CREATE INDEX idx_assignment_attempts_occurrence_end
    ON chore_assignment_attempts (occurrence_id, ended_at);

CREATE TABLE rotation_decision_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurrence_id BIGINT NOT NULL,
    decision_sequence INTEGER NOT NULL,
    trigger_type VARCHAR(40) NOT NULL,
    outcome VARCHAR(30) NOT NULL,
    no_candidate_reason VARCHAR(60),
    selected_membership_id BIGINT,
    algorithm_version VARCHAR(30) NOT NULL,
    decision_seed BIGINT NOT NULL,
    candidate_snapshot CLOB NOT NULL,
    decision_summary VARCHAR(500) NOT NULL,
    decided_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_rotation_decision_logs_occurrence_sequence
        UNIQUE (occurrence_id, decision_sequence),
    CONSTRAINT fk_rotation_decision_logs_occurrence
        FOREIGN KEY (occurrence_id) REFERENCES chore_occurrences (id),
    CONSTRAINT fk_rotation_decision_logs_selected_member
        FOREIGN KEY (selected_membership_id) REFERENCES group_members (id)
);

CREATE INDEX idx_rotation_decision_logs_occurrence
    ON rotation_decision_logs (occurrence_id);
