CREATE TABLE idempotency_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT NOT NULL,
    http_method VARCHAR(10) NOT NULL,
    normalized_uri VARCHAR(2048) NOT NULL,
    uri_hash VARCHAR(64) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    response_status INTEGER NOT NULL,
    response_body CLOB,
    response_etag VARCHAR(255),
    response_location VARCHAR(2048),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_idempotency_records_actor_method_uri_key
        UNIQUE (actor_user_id, http_method, uri_hash, idempotency_key),
    CONSTRAINT fk_idempotency_records_actor_user
        FOREIGN KEY (actor_user_id) REFERENCES users (id)
);

CREATE INDEX idx_idempotency_records_expires_at
    ON idempotency_records (expires_at);
