ALTER TABLE chore_occurrences
    ADD COLUMN chore_name_snapshot VARCHAR(100);

UPDATE chore_occurrences occurrence
SET chore_name_snapshot = (
    SELECT chore.name
    FROM chores chore
    WHERE chore.id = occurrence.chore_id
);

ALTER TABLE chore_occurrences
    ALTER COLUMN chore_name_snapshot SET NOT NULL;

ALTER TABLE chore_assignment_attempts
    ADD COLUMN completion_revoked_at TIMESTAMP(6) WITH TIME ZONE;
ALTER TABLE chore_assignment_attempts
    ADD COLUMN completion_revoked_by_membership_id BIGINT;
ALTER TABLE chore_assignment_attempts
    ADD COLUMN completion_revocation_note VARCHAR(500);

ALTER TABLE chore_assignment_attempts
    ADD CONSTRAINT fk_assignment_attempts_completion_revoked_by
        FOREIGN KEY (completion_revoked_by_membership_id)
        REFERENCES group_members (id);

CREATE INDEX idx_assignment_attempts_completion_revoked_by
    ON chore_assignment_attempts (completion_revoked_by_membership_id);

CREATE TABLE substitute_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(36) NOT NULL,
    occurrence_id BIGINT NOT NULL,
    requester_assignment_id BIGINT NOT NULL,
    eligibility_snapshot_version INTEGER NOT NULL,
    reason VARCHAR(500) NOT NULL,
    status VARCHAR(20) NOT NULL,
    accepted_assignment_id BIGINT,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    last_response_at TIMESTAMP(6) WITH TIME ZONE,
    resolved_at TIMESTAMP(6) WITH TIME ZONE,
    active_marker INTEGER,
    version BIGINT NOT NULL,
    CONSTRAINT uk_substitute_requests_public_id UNIQUE (public_id),
    CONSTRAINT uk_substitute_requests_occurrence_active
        UNIQUE (occurrence_id, active_marker),
    CONSTRAINT uk_substitute_requests_accepted_assignment
        UNIQUE (accepted_assignment_id),
    CONSTRAINT fk_substitute_requests_occurrence
        FOREIGN KEY (occurrence_id) REFERENCES chore_occurrences (id),
    CONSTRAINT fk_substitute_requests_requester_assignment
        FOREIGN KEY (requester_assignment_id) REFERENCES chore_assignment_attempts (id),
    CONSTRAINT fk_substitute_requests_accepted_assignment
        FOREIGN KEY (accepted_assignment_id) REFERENCES chore_assignment_attempts (id)
);

CREATE INDEX idx_substitute_requests_occurrence_status
    ON substitute_requests (occurrence_id, status);

CREATE TABLE substitute_request_recipients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL,
    membership_id BIGINT NOT NULL,
    member_activation_generation BIGINT NOT NULL,
    response_status VARCHAR(20) NOT NULL,
    responded_at TIMESTAMP(6) WITH TIME ZONE,
    accepted_marker INTEGER,
    version BIGINT NOT NULL,
    CONSTRAINT uk_substitute_recipients_request_member
        UNIQUE (request_id, membership_id),
    CONSTRAINT uk_substitute_recipients_one_accepted
        UNIQUE (request_id, accepted_marker),
    CONSTRAINT fk_substitute_recipients_request
        FOREIGN KEY (request_id) REFERENCES substitute_requests (id),
    CONSTRAINT fk_substitute_recipients_membership
        FOREIGN KEY (membership_id) REFERENCES group_members (id)
);

CREATE INDEX idx_substitute_recipients_member_status
    ON substitute_request_recipients (membership_id, response_status, request_id);
