CREATE TABLE spaces (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(36) NOT NULL,
    group_id BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_spaces_public_id UNIQUE (public_id),
    CONSTRAINT uk_spaces_group_name UNIQUE (group_id, name),
    CONSTRAINT fk_spaces_group
        FOREIGN KEY (group_id) REFERENCES sharing_groups (id)
);

CREATE INDEX idx_spaces_group_id
    ON spaces (group_id);

CREATE TABLE reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(36) NOT NULL,
    space_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    reservation_date DATE NOT NULL,
    start_time TIME(6) NOT NULL,
    end_time TIME(6) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    cancelled_at TIMESTAMP(6) WITH TIME ZONE,
    version BIGINT NOT NULL,
    CONSTRAINT uk_reservations_public_id UNIQUE (public_id),
    CONSTRAINT fk_reservations_space
        FOREIGN KEY (space_id) REFERENCES spaces (id),
    CONSTRAINT fk_reservations_member
        FOREIGN KEY (member_id) REFERENCES group_members (id)
);

CREATE INDEX idx_reservations_space_date
    ON reservations (space_id, reservation_date, status);
