package gdg.sharinglog.domain.rotation;

public enum AssignmentTrigger {
    INITIAL,
    DECLINE_REASSIGNMENT,
    MEMBER_LEFT_REASSIGNMENT,
    NEEDS_ATTENTION_RETRY,
    PARTICIPATION_CHANGE_REASSIGNMENT,
    PARTICIPATION_CHANGE_RETRY,
    SUBSTITUTE_ACCEPTANCE,
    COMPLETION_REOPENED
}
