#!/bin/bash
set -euo pipefail

readonly GET_CONFIG="/opt/elasticbeanstalk/bin/get-config"
readonly ACME_WEBROOT="/var/lib/letsencrypt"
readonly HTTPS_CONFIG="/etc/nginx/conf.d/https.conf"
readonly HTTP_REDIRECT_CONFIG="/etc/nginx/conf.d/http-redirect.conf"
readonly RENEWAL_HOOK="/etc/letsencrypt/renewal-hooks/deploy/50-reload-nginx.sh"

environment_value() {
    local name="$1"
    local fallback="${2:-}"
    local value="${!name:-}"

    if [[ -z "$value" && -x "$GET_CONFIG" ]]; then
        value="$("$GET_CONFIG" environment -k "$name" 2>/dev/null || true)"
    fi

    printf '%s' "${value:-$fallback}"
}

readonly HTTPS_PUBLIC_HOST="$(environment_value HTTPS_PUBLIC_HOST)"
readonly CERTBOT_EMAIL="$(environment_value CERTBOT_EMAIL)"
readonly APPLICATION_PORT="$(environment_value SERVER_PORT 5000)"

: "${HTTPS_PUBLIC_HOST:?HTTPS_PUBLIC_HOST must be set}"
: "${CERTBOT_EMAIL:?CERTBOT_EMAIL must be set}"

if [[ ! "$HTTPS_PUBLIC_HOST" =~ ^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$ ]]; then
    echo "HTTPS_PUBLIC_HOST must be a lowercase hostname without a scheme: $HTTPS_PUBLIC_HOST" >&2
    exit 1
fi

if [[ ! "$CERTBOT_EMAIL" =~ ^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$ ]]; then
    echo "CERTBOT_EMAIL must be a valid email address" >&2
    exit 1
fi

if [[ ! "$APPLICATION_PORT" =~ ^[0-9]{1,5}$ ]] \
    || (( 10#$APPLICATION_PORT < 1 || 10#$APPLICATION_PORT > 65535 )); then
    echo "SERVER_PORT must be a valid TCP port: $APPLICATION_PORT" >&2
    exit 1
fi

dnf install -y certbot python3-certbot-nginx

install -d -m 0755 \
    "$ACME_WEBROOT/.well-known/acme-challenge" \
    /etc/letsencrypt/renewal-hooks/deploy
cat > "$RENEWAL_HOOK" <<'EOF'
#!/bin/sh
systemctl reload nginx
EOF
chmod 0755 "$RENEWAL_HOOK"

# Elastic Beanstalk rewrites nginx.conf during deployments. Only let Certbot manage the
# certificate, then recreate the HTTP redirect and HTTPS proxy in separate conf.d files.
certbot certonly \
    --non-interactive \
    --agree-tos \
    --email "$CERTBOT_EMAIL" \
    --webroot \
    --webroot-path "$ACME_WEBROOT" \
    --keep-until-expiring \
    --cert-name "$HTTPS_PUBLIC_HOST" \
    -d "$HTTPS_PUBLIC_HOST"

cat > "$HTTP_REDIRECT_CONFIG" <<EOF
# Generated by .platform/scripts/configure-certbot.sh after each EB deployment.
server {
    listen 80;
    server_name $HTTPS_PUBLIC_HOST;

    location ^~ /.well-known/acme-challenge/ {
        root $ACME_WEBROOT;
        default_type text/plain;
        try_files \$uri =404;
    }

    location / {
        return 301 https://$HTTPS_PUBLIC_HOST\$request_uri;
    }
}
EOF

cat > "$HTTPS_CONFIG" <<EOF
# Generated by .platform/scripts/configure-certbot.sh after each EB deployment.
server {
    listen 443 ssl;
    server_name $HTTPS_PUBLIC_HOST;

    ssl_certificate /etc/letsencrypt/live/$HTTPS_PUBLIC_HOST/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$HTTPS_PUBLIC_HOST/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        proxy_pass http://127.0.0.1:$APPLICATION_PORT;
        proxy_http_version 1.1;

        proxy_set_header Connection \$connection_upgrade;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header X-Forwarded-Port 443;
    }
}
EOF

nginx -t
systemctl enable nginx
systemctl enable --now certbot-renew.timer
systemctl reload nginx
